/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.retailerpricecollector;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
  }
}
